export const data = [
  {
    title: "Notify  me.",
    image:
      "https://res.cloudinary.com/doaedvl5s/image/upload/v1680586453/Screenshot_185_pgk68a.png",
    desc: "Notify  me. is a blog website where use can read blog post and create post",
    techStack: [
      "html 5",
      "css 3",
      "javascript",
      "react",
      "redux",
      "react-router-dom",
      "react-icons",
      "react-redux",
      "redux-thunk",
      "chakra-u",
      "bcrypt",
      "cloudinary",
      "cors",
      "dotenv,",
      "express",
      "jsonwebtoken",
      "mongoose",
      "multer",
      "nodemon",
    ],
    live: "https://rightous.netlify.app/",
    source: "https://github.com/Praful-87/blog-app-mern",
  },
  {
    title: "AppleTv Clone",
    image:
      "https://github.com/Praful-87/ImagesDb/blob/main/Screenshot%20(167).png?raw=true",
    desc: "Apple TV+ is a streaming service featuring Apple Originals — award-winning series, compelling dramas, groundbreaking documentaries, kids' entertainment, comedies, and more.",
    techStack: [
      "html 5",
      "css 3",
      "javascript",
      "react",
      "redux",
      "react-router-dom",
      "react-icons",
      "react-redux",
      "redux-thunk",
      "chakra-u",
      "cors",
      "dotenv",
      "express",
      "monogoDb",
      "mongoDB atlas",
      "mongoose",
      "nodemon",
    ],
    live: "https://wantflix-shows.netlify.app/",
    source: "https://github.com/A-Hore/likely-laborer-9813",
  },
  {
    title: "intern and theory Clone",
    image:
      "https://github.com/Praful-87/ImagesDb/blob/main/Screenshot%20(144).png?raw=true",
    desc: "Intern theory is for upskilling yourself by enrolling in Intern theory's Online courses. Find internships for students in different cities in India.",
    techStack: [
      "html 5",
      "css 3",
      "javascript",
      "react",
      "redux",
      "react-router-dom",
      "react-redux",
      "redux-thunk",
      "chakra-u",
    ],
    live: "https://interandjob.netlify.app/",
    source: "https://github.com/udhai-20/Intern-Theory_Clone",
  },
  {
    title: "ESPNcricinfo Clone",
    image:
      "https://github.com/Praful-87/ImagesDb/blob/main/Screenshot%20(143).png?raw=true",
    desc: "ESPN cricinfo is a sports news website exclusively for the game of cricket, feed and news",
    techStack: ["Html", "Css", "Javascript"],
    live: "https://spectacular-piroshki-a8c9a4.netlify.app/landing.html",
    source: "https://github.com/surajsharma83074/espncric.info",
  },
  {
    title: "mindtickle Clone",
    image:
      "https://github.com/Praful-87/ImagesDb/blob/main/Screenshot%20(142).png?raw=true",
    desc: "Mindtickle is a Sales Readiness Platform for onboarding, product training, coaching, and ongoing readiness.",
    techStack: ["Html", "Css", "Javascript"],
    live: "https://resonant-wisp-cedb64.netlify.app/index.html",
    source: "https://github.com/Chetan0777/moving-party-2070",
  },
];
